Revert "Always log debug output to syslog"
Currently makes glean crash with:
/dev/sda2: LABEL="config-2" TYPE="iso9660" 
mount: block device /dev/sda2 is write-protected, mounting read-only
Traceback (most recent call last):
  File "/usr/local/bin/glean", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/glean/cmd.py", line 514, in main
    syslog_handler = logging.handlers.SysLogHandler('/dev/log')
  File "/usr/lib/python2.7/logging/handlers.py", line 759, in __init__
    self._connect_unixsocket(address)
  File "/usr/lib/python2.7/logging/handlers.py", line 787, in _connect_unixsocket
    self.socket.connect(address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory


This reverts commit 5733aadb2cd1634f83df7a8673c863a6084f5f04.

Change-Id: I4397e3042fc80801a774c8dc70ba17756babf877